import { Router } from "express";
import { getOutfitRecommendations, isCompleteRecommendation } from "../data/recommend";
import type { StoredWardrobeItem } from "../data/wardrobeMap";
import type { WeatherProviderResponse } from "../weather/mapWeather";
const router=Router();
const roleFor=(category:string)=>category==="accessories"?"accessory":category.endsWith("s")?category.slice(0,-1):category;
const moodFor=(tags:string[])=>tags.find((tag)=>["casual","minimal","streetwear","formal","sporty","boho","chic"].includes(tag))??"casual";
router.post("/suggest-outfits",(req,res)=>{ const body=req.body as {items?:StoredWardrobeItem[];temperature?:number;weatherCode?:number;humidity?:number;windSpeed?:number;windKmh?:number;windUnit?:WeatherProviderResponse["windUnit"];rainProbability?:number;uvIndex?:number;condition?:string;timeOfDay?:WeatherProviderResponse["timeOfDay"];hemisphere?:WeatherProviderResponse["hemisphere"];monthIndex?:number;userGender?:string;userAge?:number;styleAesthetics?:string[];colorPalette?:string}; const result=getOutfitRecommendations({items:Array.isArray(body.items)?body.items:[],weather:{temperature:body.temperature,weatherCode:body.weatherCode,humidity:body.humidity,windSpeed:body.windSpeed,windKmh:body.windKmh,windUnit:body.windUnit,rainProbability:body.rainProbability,uvIndex:body.uvIndex,condition:body.condition,timeOfDay:body.timeOfDay,hemisphere:body.hemisphere,monthIndex:body.monthIndex},user:{userGender:body.userGender,userAge:body.userAge,styleAesthetics:body.styleAesthetics,colorPalette:body.colorPalette}}); if(!isCompleteRecommendation(result)){const partial=result.bestPartial.map((item)=>({itemId:item.id,role:roleFor(item.category)}));res.json({outfits:partial.length?[{name:"Best available look",mood:"casual",weatherNote:result.message,isComplete:false,items:partial}]:[],incomplete:true,missing:result.missing,message:result.message,suggestedAddition:result.suggestedAddition});return;} res.json({outfits:result.map((entry,index)=>({name:index===0?"Best for today":`Weather-ready look ${index+1}`,mood:moodFor(entry.outfit.flatMap((item)=>item.tags)),weatherNote:entry.why.join(" · ")||"Matched to today’s conditions",isComplete:true,items:entry.outfit.map((item)=>({itemId:item.id,role:roleFor(item.category)}))})),scores:result.map((entry)=>entry.score),reasons:result.map((entry)=>entry.why)}); });
export default router;
