import type { Condition, Weather } from "../engine/weatherEngine";
export interface WeatherProviderResponse { temperature?:number; tempC?:number; weatherCode?:number; condition?:string; rainProbability?:number; precipitationProbability?:number; precipitation_probability?:number; windSpeed?:number; windKmh?:number; windUnit?:"km/h"|"kph"|"m/s"|"mph"; humidity?:number; uvIndex?:number; timeOfDay?:Weather["timeOfDay"]; hemisphere?:Weather["hemisphere"]; monthIndex?:number; current?:Record<string,unknown>; current_units?:Record<string,unknown>; }
const num = (...values: unknown[]) => { for (const value of values) { const n=typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN; if (Number.isFinite(n)) return n; } return undefined; };
const clamp = (value:number|undefined, min:number, max:number) => value === undefined ? undefined : Math.max(min,Math.min(max,value));
function fromCode(code:number|undefined):Condition { if (code !== undefined && code>=71 && code<=77) return "snowy"; if (code !== undefined && ((code>=51 && code<=67)||(code>=80 && code<=99))) return "rainy"; return code !== undefined && code>=2 && code<=48 ? "cloudy" : "clear"; }
function condition(value:unknown, code?:number):Condition { const s=typeof value === "string" ? value.toLowerCase() : ""; if(/snow/.test(s))return "snowy"; if(/rain|drizzle|storm/.test(s))return "rainy"; if(/wind/.test(s))return "windy"; if(/humid/.test(s))return "humid"; if(/hot|heat/.test(s))return "hot"; if(/cloud|fog|overcast/.test(s))return "cloudy"; return fromCode(code); }
function time():Weather["timeOfDay"] { const h=new Date().getHours(); return h<6||h>=22?"night":h<11?"morning":h<18?"day":"evening"; }
/** Unit-safe mapper for Open-Meteo and Lookly's existing weather payload. */
export function mapWeather(source:WeatherProviderResponse):Weather { const current=source.current??{}, units=source.current_units??{}; const code=num(source.weatherCode,current.weather_code); const wind=num(source.windKmh,source.windSpeed,current.wind_speed_10m); const unit=source.windUnit??units.wind_speed_10m; const windKmh=wind===undefined?undefined:unit==="m/s"?wind*3.6:unit==="mph"?wind*1.609:wind; const rain=num(source.rainProbability,source.precipitationProbability,source.precipitation_probability,current.precipitation_probability); return { tempC:num(source.tempC,source.temperature,current.temperature_2m)??20, condition:condition(source.condition,code), rainProbability:rain===undefined?undefined:clamp(rain>1?rain/100:rain,0,1), windKmh:clamp(windKmh,0,300), humidity:clamp(num(source.humidity,current.relative_humidity_2m),0,100), uvIndex:clamp(num(source.uvIndex,current.uv_index),0,20), timeOfDay:source.timeOfDay??time(), hemisphere:source.hemisphere, monthIndex:clamp(source.monthIndex,0,11) }; }
