export type AppLanguage = "en" | "ru" | "uz";

type LocalizedValues = Record<AppLanguage, Record<string, string>>;

/** Strings added outside the original catalogue while older installations migrate. */
export const supplementalTranslations: LocalizedValues = {
  en: {
    account_security: "Account & security",
    account_security_desc: "View and update your sign-in details.",
    account_editor_desc: "Keep your email current and choose a new password whenever you need one.",
    email_address: "Email address",
    password: "Password",
    email_change_hint: "You may need to confirm the new address before it replaces your current email.",
    update_email: "Update email",
    password_security_hint: "Your current password cannot be displayed. Enter a new password below to replace it.",
    new_password: "New password (at least 6 characters)",
    confirm_new_password: "Confirm new password",
    show_password: "Show password",
    hide_password: "Hide password",
    update_password: "Update password",
    invalid_email_title: "Check your email",
    invalid_email_message: "Enter a valid email address.",
    email_unchanged_title: "Email unchanged",
    email_unchanged_message: "This is already your account email.",
    email_update_failed: "Couldn't update email",
    verify_new_email_title: "Confirm your new email",
    verify_new_email_message: "We sent a confirmation link to your new email address. Your current email remains active until you confirm it.",
    email_updated_title: "Email updated",
    email_updated_message: "Your sign-in email has been updated.",
    password_too_short_title: "Password is too short",
    password_too_short_message: "Use at least 6 characters.",
    password_mismatch_title: "Passwords don't match",
    password_mismatch_message: "Enter the same new password in both fields.",
    password_update_failed: "Couldn't update password",
    password_updated_title: "Password updated",
    password_updated_message: "Use your new password the next time you sign in.",
    account_connection_error: "Check your connection and try again.",
    wardrobe_search: "Search your wardrobe",
    image_unavailable: "Product image unavailable",
    personal_details: "Personal details",
    edit_gender_age: "Edit gender and age",
    edit_name_gender_age: "Edit name, gender and age",
    choose_age: "Scroll vertically to choose your age",
    save_changes: "Save changes",
    done: "Done",
    tap_to_refresh: "Tap to refresh",
    report_bug: "Report a bug",
    report_bug_desc: "Describe a problem and attach a screenshot.",
    report_bug_prompt: "Tell us what happened. A screenshot is optional.",
    send_report: "Send report",
    privacy_title: "Your privacy", privacy_short_desc: "Your wardrobe, photos and saved looks are private to your account.", not_set: "Not set",
    privacy_account_desc: "Your wardrobe, personal names, body reference photo and saved looks are private to your signed-in account. Other Lookly users cannot browse them.",
    about_message: "Lookly 1.0.0 pilot\nYour wardrobe remains private to your account.",
    weather_location_title: "Weather location",
    weather_location_prompt: "Choose a city or let Lookly use your current location.",
    city_placeholder: "e.g. Samarkand, Uzbekistan", bug_placeholder: "What were you trying to do? What happened instead?",
    suggested_places: "Suggested places",
    no_city_suggestion: "No suggested city yet — you can still save this location.",
    use_current_location: "Use current location",
    save_location: "Save location",
    weather_clear_sky: "Clear sky",
    weather_partly_cloudy: "Partly cloudy",
    weather_fog: "Fog",
    weather_light_drizzle: "Light drizzle",
    weather_rain_showers: "Rain showers",
    weather_snow: "Snow",
    weather_heavy_showers: "Heavy showers",
    weather_thunderstorm: "Thunderstorm",
    weather_unknown: "Unknown",
    season_spring: "Spring", season_summer: "Summer", season_fall: "Fall", season_winter: "Winter",
    color_black: "Black", color_white: "White", color_beige: "Beige", color_navy: "Navy", color_camel: "Camel", color_burgundy: "Burgundy", color_olive: "Olive", color_gray: "Gray", color_blush: "Blush", color_denim: "Denim", color_terracotta: "Terracotta", color_cream: "Cream",
    add_item: "Add Item", scan_with_ai: "Scan with AI", detecting_items: "Detecting items…", isolating_garment: "Isolating garment…", filled_automatically: "Filled automatically",
    cancel_upload: "Cancel upload", fabric_material: "FABRIC / MATERIAL", item_name: "Item name", item_name_hint: "AI suggests a name. Edit it to any personal name you prefer.", category: "Category", footwear_type: "Footwear type", footwear_hint: "Prevents sandals from being suggested for rain or cool weather", color: "Color", seasons: "Seasons", fabric_weight: "Fabric weight", workwear_uniform: "Workwear / Uniform",
    item_details: "Item Details", personal_name_optional: "Personal name (optional)", restore_ai_name: "Clear it and save to restore the AI name as the title.", save: "Save", style_this_item: "Style This Item",
    outfit_calendar_label: "OUTFIT CALENDAR", what_i_wore: "What I Wore", log_today: "Log today", log_outfit: "Log outfit", recent_logs: "RECENT LOGS", add_note_optional: "ADD A NOTE (OPTIONAL)", no_items: "No items", no_outfit_logged: "No outfit logged for this day", logging_outfit_for: "Logging outfit for", no_outfit_selected: "No outfit items selected. Log a blank note or go back to the outfit builder.", note_placeholder: "e.g. wore this to a meeting…",
    styling: "Styling…", shuffle_extra_hint: "surfaces rarely-worn pieces & bold colour contrasts.",
  },
  ru: {
    account_security: "Аккаунт и безопасность",
    account_security_desc: "Просматривайте и изменяйте данные для входа.",
    account_editor_desc: "Обновляйте электронную почту и при необходимости задавайте новый пароль.",
    email_address: "Электронная почта",
    password: "Пароль",
    email_change_hint: "Возможно, новый адрес потребуется подтвердить, прежде чем он заменит текущий.",
    update_email: "Обновить почту",
    password_security_hint: "Текущий пароль нельзя отобразить. Введите новый пароль ниже, чтобы заменить его.",
    new_password: "Новый пароль (минимум 6 символов)",
    confirm_new_password: "Подтвердите новый пароль",
    show_password: "Показать пароль",
    hide_password: "Скрыть пароль",
    update_password: "Обновить пароль",
    invalid_email_title: "Проверьте адрес",
    invalid_email_message: "Введите действительный адрес электронной почты.",
    email_unchanged_title: "Почта не изменена",
    email_unchanged_message: "Этот адрес уже используется для вашего аккаунта.",
    email_update_failed: "Не удалось обновить почту",
    verify_new_email_title: "Подтвердите новую почту",
    verify_new_email_message: "Мы отправили ссылку для подтверждения на новый адрес. Текущий адрес останется активным до подтверждения.",
    email_updated_title: "Почта обновлена",
    email_updated_message: "Адрес для входа обновлён.",
    password_too_short_title: "Пароль слишком короткий",
    password_too_short_message: "Используйте не менее 6 символов.",
    password_mismatch_title: "Пароли не совпадают",
    password_mismatch_message: "Введите одинаковый новый пароль в обоих полях.",
    password_update_failed: "Не удалось обновить пароль",
    password_updated_title: "Пароль обновлён",
    password_updated_message: "При следующем входе используйте новый пароль.",
    account_connection_error: "Проверьте подключение и повторите попытку.",
    wardrobe_search: "Поиск в гардеробе",
    image_unavailable: "Изображение недоступно",
    personal_details: "Личные данные",
    edit_gender_age: "Изменить пол и возраст",
    edit_name_gender_age: "Изменить имя, пол и возраст",
    choose_age: "Прокрутите, чтобы выбрать возраст",
    save_changes: "Сохранить изменения",
    done: "Готово",
    tap_to_refresh: "Нажмите, чтобы обновить",
    report_bug: "Сообщить об ошибке",
    report_bug_desc: "Опишите проблему и прикрепите снимок экрана.",
    report_bug_prompt: "Расскажите, что произошло. Снимок экрана необязателен.",
    send_report: "Отправить отчёт",
    privacy_title: "Ваша конфиденциальность", privacy_short_desc: "Ваш гардероб, фотографии и сохранённые образы доступны только в вашей учётной записи.", not_set: "Не указано",
    privacy_account_desc: "Ваш гардероб, личные названия, фото тела и сохранённые образы доступны только в вашей учётной записи. Другие пользователи Lookly не могут их просматривать.",
    about_message: "Пилотная версия Lookly 1.0.0\nВаш гардероб доступен только в вашей учётной записи.",
    weather_location_title: "Местоположение погоды",
    weather_location_prompt: "Выберите город или разрешите Lookly использовать ваше текущее местоположение.",
    city_placeholder: "например, Самарканд, Узбекистан", bug_placeholder: "Что вы пытались сделать? Что произошло вместо этого?",
    suggested_places: "Предлагаемые места",
    no_city_suggestion: "Предложений пока нет — это место всё равно можно сохранить.",
    use_current_location: "Использовать текущее местоположение",
    save_location: "Сохранить местоположение",
    weather_clear_sky: "Ясное небо",
    weather_partly_cloudy: "Переменная облачность",
    weather_fog: "Туман",
    weather_light_drizzle: "Небольшая морось",
    weather_rain_showers: "Ливни",
    weather_snow: "Снег",
    weather_heavy_showers: "Сильные ливни",
    weather_thunderstorm: "Гроза",
    weather_unknown: "Неизвестно",
    season_spring: "Весна", season_summer: "Лето", season_fall: "Осень", season_winter: "Зима",
    color_black: "Чёрный", color_white: "Белый", color_beige: "Бежевый", color_navy: "Тёмно-синий", color_camel: "Верблюжий", color_burgundy: "Бордовый", color_olive: "Оливковый", color_gray: "Серый", color_blush: "Пудровый", color_denim: "Джинсовый", color_terracotta: "Терракотовый", color_cream: "Кремовый",
    add_item: "Добавить вещь", scan_with_ai: "Распознать с ИИ", detecting_items: "Распознаём вещи…", isolating_garment: "Выделяем вещь…", filled_automatically: "Заполнено автоматически",
    cancel_upload: "Отменить загрузку", fabric_material: "ТКАНЬ / МАТЕРИАЛ", item_name: "Название вещи", item_name_hint: "ИИ предлагает название. Вы можете заменить его своим.", category: "Категория", footwear_type: "Тип обуви", footwear_hint: "Не позволяет предлагать сандалии в дождь или прохладную погоду", color: "Цвет", seasons: "Сезоны", fabric_weight: "Плотность ткани", workwear_uniform: "Рабочая одежда / форма",
    item_details: "Сведения о вещи", personal_name_optional: "Личное название (необязательно)", restore_ai_name: "Очистите поле и сохраните, чтобы вернуть название ИИ.", save: "Сохранить", style_this_item: "Создать образ с вещью",
    outfit_calendar_label: "КАЛЕНДАРЬ ОБРАЗОВ", what_i_wore: "Что я носил(а)", log_today: "Записать сегодня", log_outfit: "Записать образ", recent_logs: "НЕДАВНИЕ ЗАПИСИ", add_note_optional: "ДОБАВИТЬ ЗАМЕТКУ (НЕОБЯЗАТЕЛЬНО)", no_items: "Нет вещей", no_outfit_logged: "На этот день образ не записан", logging_outfit_for: "Запись образа на", no_outfit_selected: "Вещи не выбраны. Добавьте заметку или вернитесь в конструктор образа.", note_placeholder: "например, надел(а) это на встречу…",
    styling: "Подбираем…", shuffle_extra_hint: "показывает редко носимые вещи и смелые цветовые сочетания.",
  },
  uz: {
    account_security: "Hisob va xavfsizlik",
    account_security_desc: "Kirish ma'lumotlaringizni ko'ring va yangilang.",
    account_editor_desc: "Email manzilingizni yangilang va kerak bo'lganda yangi parol tanlang.",
    email_address: "Email manzil",
    password: "Parol",
    email_change_hint: "Yangi manzil joriy emailingizni almashtirishidan oldin uni tasdiqlashingiz kerak bo'lishi mumkin.",
    update_email: "Emailni yangilash",
    password_security_hint: "Joriy parolni ko'rsatib bo'lmaydi. Uni almashtirish uchun quyida yangi parol kiriting.",
    new_password: "Yangi parol (kamida 6 ta belgi)",
    confirm_new_password: "Yangi parolni tasdiqlang",
    show_password: "Parolni ko'rsatish",
    hide_password: "Parolni yashirish",
    update_password: "Parolni yangilash",
    invalid_email_title: "Emailni tekshiring",
    invalid_email_message: "To'g'ri email manzilini kiriting.",
    email_unchanged_title: "Email o'zgarmadi",
    email_unchanged_message: "Bu allaqachon hisobingiz emaili.",
    email_update_failed: "Emailni yangilab bo'lmadi",
    verify_new_email_title: "Yangi emailni tasdiqlang",
    verify_new_email_message: "Yangi email manzilingizga tasdiqlash havolasini yubordik. Tasdiqlamaguningizcha joriy emailingiz faol qoladi.",
    email_updated_title: "Email yangilandi",
    email_updated_message: "Kirish emailingiz yangilandi.",
    password_too_short_title: "Parol juda qisqa",
    password_too_short_message: "Kamida 6 ta belgidan foydalaning.",
    password_mismatch_title: "Parollar mos kelmadi",
    password_mismatch_message: "Ikkala maydonga ham bir xil yangi parolni kiriting.",
    password_update_failed: "Parolni yangilab bo'lmadi",
    password_updated_title: "Parol yangilandi",
    password_updated_message: "Keyingi kirishda yangi parolingizdan foydalaning.",
    account_connection_error: "Ulanishni tekshirib, qayta urinib ko'ring.",
    wardrobe_search: "Garderobdan qidirish",
    image_unavailable: "Mahsulot rasmi mavjud emas",
    personal_details: "Shaxsiy ma'lumotlar",
    edit_gender_age: "Jins va yoshni o'zgartirish",
    edit_name_gender_age: "Ism, jins va yoshni o'zgartirish",
    choose_age: "Yoshingizni tanlash uchun aylantiring",
    save_changes: "O'zgarishlarni saqlash",
    done: "Tayyor",
    tap_to_refresh: "Yangilash uchun bosing",
    report_bug: "Xato haqida xabar berish",
    report_bug_desc: "Muammoni tasvirlab, ekran rasmini biriktiring.",
    report_bug_prompt: "Nima bo'lganini ayting. Ekran rasmi ixtiyoriy.",
    send_report: "Hisobotni yuborish",
    privacy_title: "Maxfiyligingiz", privacy_short_desc: "Garderobingiz, rasmlaringiz va saqlangan ko'rinishlar faqat hisobingizda ko'rinadi.", not_set: "Ko'rsatilmagan",
    privacy_account_desc: "Garderobingiz, shaxsiy nomlar, tana rasmi va saqlangan ko'rinishlar faqat hisobingizda ko'rinadi. Boshqa Lookly foydalanuvchilari ularni ko'ra olmaydi.",
    about_message: "Lookly 1.0.0 sinov versiyasi\nGarderobingiz faqat hisobingizda ko'rinadi.",
    weather_location_title: "Ob-havo joylashuvi",
    weather_location_prompt: "Shaharni tanlang yoki Lookly'ga joriy joylashuvingizdan foydalanishga ruxsat bering.",
    city_placeholder: "masalan, Samarqand, O'zbekiston", bug_placeholder: "Nima qilmoqchi edingiz? Buning o'rniga nima sodir bo'ldi?",
    suggested_places: "Tavsiya etilgan joylar",
    no_city_suggestion: "Hozircha taklif yo'q — bu joylashuvni baribir saqlashingiz mumkin.",
    use_current_location: "Joriy joylashuvdan foydalanish",
    save_location: "Joylashuvni saqlash",
    weather_clear_sky: "Ochiq osmon",
    weather_partly_cloudy: "Qisman bulutli",
    weather_fog: "Tuman",
    weather_light_drizzle: "Yengil yomg'ir",
    weather_rain_showers: "Yomg'irli",
    weather_snow: "Qor",
    weather_heavy_showers: "Kuchli yomg'ir",
    weather_thunderstorm: "Momaqaldiroq",
    weather_unknown: "Noma'lum",
    season_spring: "Bahor", season_summer: "Yoz", season_fall: "Kuz", season_winter: "Qish",
    color_black: "Qora", color_white: "Oq", color_beige: "Bej", color_navy: "To'q ko'k", color_camel: "Tuya rang", color_burgundy: "Bordo", color_olive: "Zaytun rang", color_gray: "Kulrang", color_blush: "Pushti", color_denim: "Jinsi", color_terracotta: "Terrakota", color_cream: "Krem rang",
    add_item: "Kiyim qo'shish", scan_with_ai: "AI bilan aniqlash", detecting_items: "Kiyimlar aniqlanmoqda…", isolating_garment: "Kiyim ajratilmoqda…", filled_automatically: "Avtomatik to'ldirildi",
    cancel_upload: "Yuklashni bekor qilish", fabric_material: "MATO / MATERIAL", item_name: "Kiyim nomi", item_name_hint: "AI nom taklif qiladi. Uni o'zingiz xohlagan nomga o'zgartiring.", category: "Toifa", footwear_type: "Poyabzal turi", footwear_hint: "Yomg'irli yoki salqin havoda sandal tavsiya qilinishining oldini oladi", color: "Rang", seasons: "Fasllar", fabric_weight: "Mato qalinligi", workwear_uniform: "Ish kiyimi / forma",
    item_details: "Kiyim tafsilotlari", personal_name_optional: "Shaxsiy nom (ixtiyoriy)", restore_ai_name: "AI nomini qaytarish uchun maydonni tozalab saqlang.", save: "Saqlash", style_this_item: "Bu kiyim bilan ko'rinish yaratish",
    outfit_calendar_label: "KO'RINISHLAR TAQVIMI", what_i_wore: "Nima kiydim", log_today: "Bugunni yozish", log_outfit: "Ko'rinishni yozish", recent_logs: "SO'NGGI YOZUVLAR", add_note_optional: "IZOH QO'SHISH (IXTIYORIY)", no_items: "Kiyimlar yo'q", no_outfit_logged: "Bu kun uchun ko'rinish yozilmagan", logging_outfit_for: "Ko'rinish yozilayotgan sana", no_outfit_selected: "Kiyimlar tanlanmagan. Izoh yozing yoki ko'rinish yaratuvchisiga qayting.", note_placeholder: "masalan, uchrashuvga shuni kiydim…",
    styling: "Tanlanmoqda…", shuffle_extra_hint: "kam kiyilgan buyumlar va dadil rang uyg'unliklarini ko'rsatadi.",
  },
};

const phraseMaps: Record<Exclude<AppLanguage, "en">, Array<[RegExp, string]>> = {
  ru: [
    [/black oversized (?:cotton )?(?:t-shirt|tee)/gi, "чёрная хлопковая футболка оверсайз"],
    [/olive green linen blend button-down shirt/gi, "оливковая льняная рубашка на пуговицах"], [/red and black wristwatch/gi, "красно-чёрные наручные часы"], [/olive green long-sleeve button-down shirt/gi, "оливковая рубашка с длинным рукавом"], [/burgundy textured long-sleeved shirt/gi, "бордовая фактурная рубашка с длинным рукавом"], [/black digital wrist watch/gi, "чёрные цифровые наручные часы"], [/burgundy short-sleeve button-down shirt/gi, "бордовая рубашка с коротким рукавом"], [/gray tailored trousers/gi, "серые классические брюки"], [/black smart band/gi, "чёрный фитнес-браслет"], [/beige chino (?:trousers|pants)/gi, "бежевые брюки чинос"], [/olive long-sleeve button-down shirt/gi, "оливковая рубашка с длинным рукавом"], [/black short-sleeve button-down shirt/gi, "чёрная рубашка с коротким рукавом"], [/black oversized (?:cotton )?tee/gi, "чёрная хлопковая футболка оверсайз"], [/white athletic sneakers/gi, "белые спортивные кроссовки"], [/black athletic shorts/gi, "чёрные спортивные шорты"], [/lime green athletic crew socks/gi, "салатовые спортивные носки"], [/navy(?: blue)? lace-up sneakers/gi, "тёмно-синие кроссовки на шнуровке"], [/black leather slide sandals/gi, "чёрные кожаные сандалии"],
    [/smartphone with case/gi, "смартфон в чехле"], [/long-sleeve polo shirt/gi, "поло с длинным рукавом"], [/relaxed-fit trousers/gi, "брюки свободного кроя"],
    [/button-down shirt/gi, "рубашка на пуговицах"], [/zip-up hoodie/gi, "худи на молнии"], [/slim-fit jeans/gi, "джинсы зауженного кроя"], [/leather sneakers/gi, "кожаные кроссовки"],
    [/t-shirt|tee\b/gi, "футболка"], [/shirt/gi, "рубашка"], [/trousers|pants/gi, "брюки"], [/jeans/gi, "джинсы"], [/dress/gi, "платье"], [/jacket/gi, "куртка"], [/coat/gi, "пальто"], [/sneakers/gi, "кроссовки"], [/shoes/gi, "обувь"], [/socks/gi, "носки"], [/bag/gi, "сумка"], [/accessories/gi, "аксессуары"],
    [/textured/gi, "фактурное"], [/oversized/gi, "оверсайз"], [/relaxed-fit/gi, "свободного кроя"], [/black/gi, "чёрное"], [/white/gi, "белое"], [/cream/gi, "кремовые"], [/navy blue|navy/gi, "тёмно-синий"], [/brown/gi, "коричневые"], [/grey|gray/gi, "серое"], [/blue/gi, "синие"], [/cotton/gi, "хлопковая"], [/linen/gi, "льняная"], [/leather/gi, "кожаные"],
  ],
  uz: [
    [/black oversized (?:cotton )?(?:t-shirt|tee)/gi, "qora oversayz paxtali futbolka"],
    [/olive green linen blend button-down shirt/gi, "zaytun rang zig'ir aralash tugmali ko'ylak"], [/red and black wristwatch/gi, "qizil-qora qo'l soati"], [/olive green long-sleeve button-down shirt/gi, "zaytun rang uzun yengli tugmali ko'ylak"], [/burgundy textured long-sleeved shirt/gi, "bordo teksturali uzun yengli ko'ylak"], [/black digital wrist watch/gi, "qora raqamli qo'l soati"], [/burgundy short-sleeve button-down shirt/gi, "bordo kalta yengli tugmali ko'ylak"], [/gray tailored trousers/gi, "kulrang klassik shim"], [/black smart band/gi, "qora fitnes bilaguzuk"], [/beige chino (?:trousers|pants)/gi, "bej chinos shim"], [/olive long-sleeve button-down shirt/gi, "zaytun rang uzun yengli tugmali ko'ylak"], [/black short-sleeve button-down shirt/gi, "qora kalta yengli tugmali ko'ylak"], [/black oversized (?:cotton )?tee/gi, "qora oversayz paxtali futbolka"], [/white athletic sneakers/gi, "oq sport krossovkasi"], [/black athletic shorts/gi, "qora sport shortigi"], [/lime green athletic crew socks/gi, "och yashil sport paypog'i"], [/navy(?: blue)? lace-up sneakers/gi, "to'q ko'k bog'ichli krossovka"], [/black leather slide sandals/gi, "qora charm sandal"],
    [/smartphone with case/gi, "g'ilofli smartfon"], [/long-sleeve polo shirt/gi, "uzun yengli polo ko'ylak"], [/relaxed-fit trousers/gi, "erkin bichimli shim"],
    [/button-down shirt/gi, "tugmali ko'ylak"], [/zip-up hoodie/gi, "fermuarli hudi"], [/slim-fit jeans/gi, "tor bichimli jinsi"], [/leather sneakers/gi, "charm krossovka"],
    [/t-shirt|tee\b/gi, "futbolka"], [/shirt/gi, "ko'ylak"], [/trousers|pants/gi, "shim"], [/jeans/gi, "jinsi"], [/dress/gi, "ko'ylak"], [/jacket/gi, "kurtka"], [/coat/gi, "palto"], [/sneakers/gi, "krossovka"], [/shoes/gi, "poyabzal"], [/socks/gi, "paypoq"], [/bag/gi, "sumka"], [/accessories/gi, "aksessuarlar"],
    [/textured/gi, "teksturali"], [/oversized/gi, "oversayz"], [/relaxed-fit/gi, "erkin bichimli"], [/black/gi, "qora"], [/white/gi, "oq"], [/cream/gi, "krem rang"], [/navy blue|navy/gi, "to'q ko'k"], [/brown/gi, "jigarrang"], [/grey|gray/gi, "kulrang"], [/blue/gi, "ko'k"], [/cotton/gi, "paxtali"], [/linen/gi, "zig'ir matoli"], [/leather/gi, "charm"],
  ],
};

/** Best-effort migration for AI names saved before localized names were stored. */
export function translateGeneratedClothingName(name: string, lang: AppLanguage): string {
  if (lang === "en" || !name.trim()) return name;
  let translated = name;
  for (const [pattern, replacement] of phraseMaps[lang]) translated = translated.replace(pattern, replacement);
  return translated.replace(/\s+/g, " ").trim().replace(/^./, (letter) => letter.toUpperCase());
}
